#! /usr/bin/env php

<?php

set_time_limit(0);

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} elseif (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    throw new RuntimeException('External libraries not found');
}

use Gotrecillo\BackpackInstaller\App;

$app = new App(new \Gotrecillo\BackpackInstaller\Config\Config(), new \League\Container\Container());

$app->addCommands([
    new \Gotrecillo\BackpackInstaller\Console\NewCommand,
    new \Gotrecillo\BackpackInstaller\Console\ConfigListCommand,
    new \Gotrecillo\BackpackInstaller\Console\SetConfigCommand,
]);

$app->run();
