#! /usr/bin/env php

<?php

use Gotrecillo\BackpackInstaller\App;

require 'vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$app = new App(new \Gotrecillo\BackpackInstaller\Config\Config(), new \League\Container\Container());

$app->addCommands([new \Gotrecillo\BackpackInstaller\NewCommand]);

$app->run();
