#! /usr/bin/env php

<?php

use Backpack\Install\App;

require 'vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$app = new App(new \Backpack\Install\Config\Config(), new \League\Container\Container());

$app->addCommands([new \Backpack\Install\NewCommand]);

$app->run();
