#! /usr/bin/env php

<?php

use Gotrecillo\BackpackInstaller\App;

require 'vendor/autoload.php';

$app = new App(new \Gotrecillo\BackpackInstaller\Config\Config(), new \League\Container\Container());

$app->addCommands([
    new \Gotrecillo\BackpackInstaller\Console\NewCommand,
    new \Gotrecillo\BackpackInstaller\Console\ConfigListCommand,
    new \Gotrecillo\BackpackInstaller\Console\SetConfigCommand,
]);

$app->run();
